### ISSUE TITLE
Remove dependency on odio urdf fork 

### ISSUE THREAD

**Issue by CarlottaSartore** [ami-iit/comodo#15]
In the documentation we depend on git+https://github.com/akhilsathuluri/odio_urdf.git@comodo it would be great to remove this dependency in favor of https://github.com/ami-iit/amo-urdf. What do you think @akhilsathuluri  ?

**Comment by akhilsathuluri** [comment]
The dependency is now removed in the new PR: https://github.com/ami-iit/comodo/pull/16

> [!NOTE]  
> Installing amo_urdf currently triggers login ID and password since it is private. Prerequisites for this commit are: 
> - [ ] Completing the populate amo_urdf merge (https://github.com/ami-iit/amo_urdf/pull/1)
> - [ ] Making the amo_urdf public, @traversaro 

@CarlottaSartore , Please check the merge and close the issue as you seem fit.

**Comment by traversaro** [comment]
Done the repo is now public.

**Comment by CarlottaSartore** [comment]
Thank you @akhilsathuluri ! Closing the issue !
